name: Deploy to Firebase

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4.1.0
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v3.8.1
      with: 
        node-version: ${{ matrix.node-version }}

    - run: npm i
    - run: npm install -g firebase-tools
    - run: npm run build
    - name: Archive Build   
      uses: actions/upload-artifact@v3.1.3
      with: 
        name: build
        path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Download Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: build
          path: build 
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

